APP_NAME: "server"
APP_PORT: "8000"

DB_DRIVER: "postgres"
DB_HOST: "localhost"
DB_PORT: 5432
DB_NAME: "bankapp"
<<<<<<< HEAD
DB_USER: "root"
DB_PASSWORD: "root123"
=======
DB_USER: "pratik"
DB_PASSWORD: "pratik"
>>>>>>> b01e0156d4c74055719a3b604dbd310e39f4083e
DB_MAX_POOL_SIZE: 5
DB_MAX_OPEN_CONS: 5
DB_MAX_LIFE_TIME_MINS: 30
MIGRATION_PATH: "./migrations"
