APP_NAME: "server"
APP_PORT: "8000"

DB_DRIVER: "postgres"
DB_HOST: "localhost"
DB_PORT: 5432
DB_NAME: "bankapp"
DB_USER: "shubham"
DB_PASSWORD: "mypass"
DB_MAX_POOL_SIZE: 5
DB_MAX_OPEN_CONS: 5
DB_MAX_LIFE_TIME_MINS: 30 
MIGRATION_PATH: "./migrations"

#JWT Signature
JWT_SECRECT_KEY: "my_secret_key"
TOKEN_EXPIRY: 30