// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	user "bankapp/user"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req
func (_m *Service) Create(ctx context.Context, req user.CreateRequest) error {
	ret := _m.Called(ctx, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, user.CreateRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByID provides a mock function with given fields: ctx, id
func (_m *Service) DeleteByID(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, req, userId
func (_m *Service) Update(ctx context.Context, req user.UpdateRequest, userId string) error {
	ret := _m.Called(ctx, req, userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, user.UpdateRequest, string) error); ok {
		r0 = rf(ctx, req, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
